# Run this with docker run -d --name consul -p 53:53 -p 53:53/udp generalmeow/consul-64bit
FROM ubuntu:16.04
MAINTAINER Paul Hoang 2016-06-26
RUN ["apt-get", "update", "-y"]
RUN ["apt-get", "install", "-y", "--no-install-recommends", "apt-utils"]
RUN ["apt-get", "upgrade", "-y"]

#install bind, default version as of 2016-06-26
ADD ./etc/bind/db.10 /etc/bind/db.10
ADD ./etc/bind/db.paulhoang.com /etc/bind/db.paulhoang.com
VOLUME /etc/bind
EXPOSE 53

#CMD ["/bin/bash"]
