# run: docker build -t generalmeow/kafka:<TAG>
# run: docker run -d -p 9092:9092 --name kafka --link zookeeper:zookeeper -e KAFKA_HEAP_OPTS='-Xmx512M -Xms512M' generalmeow/kafka:1.0-arm
FROM larmog/armhf-alpine-java:jdk-8u73
MAINTAINER Paul Hoang 2016-12-26
ENV KAFKA_HEAP_OPTS='-Xmx512M -Xms512M'
RUN ["mkdir", "-p", "/home/kafka"]
ADD ./kafka_2.11-0.10.1.0.tgz /home/kafka
COPY ["./dockerConfig", "/home/kafka/dockerConfig"]
WORKDIR /home/kafka
EXPOSE 9092
ENTRYPOINT ["/home/kafka/kafka_2.11-0.10.1.0/bin/kafka-server-start.sh", "/home/kafka/dockerConfig/server-arm.properties"]
