version: "2"

services:
  zookeeper:
    container_name: "zookeeper"
    image: "generalmeow/kafkazookeeper:1.1-arm"
    ports:
      - "2181:2181"
  kafka:
    container_name: "kafka"
    image: "generalmeow/kafka:1.1-arm"
    ports:
      - "9092:9092"
    links:
      - "zookeeper"
